services:
  - type: web
    plan: free
    name: Duderename
    env: python bot.py
    buildCommand: pip install -r requirements.txt
    startCommand: python3 bot.py
    repo: https://github.com/monitg/DUDE_RENAME.git      
    branch: master
    envVars:
      - key: BOT_TOKEN 
        sync: false
      - key: API_ID 
        sync: false
      - key: API_HASH
        sync: false
      - key: ADMIN
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_URL
        sync: false 
      - key: START_PIC
        sync: false
      - key: FORCE_SUB
        sync: false
      - key: FLOOD 
        sync: false
    autoDeploy: false
